service:
  name: igniteserverless
plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dyanamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
    name: aws
    runtime: nodejs14.x
    region: us-east-1

functions:
  create:
    handler: src/functions/create.handleCreate
    events:
      - http:
          path: /create/:id
          method: POST
          cors: true

resources:
    Resources:
      createUser:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: users
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
          AttributesDefinitions:
            - AttributeName: id
            - AttributeType: S
          KeySchema:
            - AttributeName: id
            - Key: HASH
